ARG ELK_VERSION
FROM docker.elastic.co/logstash/logstash:$ELK_VERSION

USER root

RUN yum install -y unzip sudo
RUN ln -s /usr/share/logstash /etc/logstash

USER logstash

RUN /usr/share/logstash/bin/logstash-plugin install logstash-codec-sflow
RUN /usr/share/logstash/bin/logstash-plugin update logstash-codec-netflow
RUN /usr/share/logstash/bin/logstash-plugin update logstash-input-udp
RUN /usr/share/logstash/bin/logstash-plugin update logstash-filter-dns
RUN cd /tmp && curl -L https://github.com/robcowart/elastiflow/archive/master.zip -o master.zip && \
    unzip master.zip && cp -a elastiflow-master/logstash/elastiflow/. /usr/share/logstash/elastiflow/

RUN sed -i 's/-Xms1g/-Xms4g/g' /usr/share/logstash/config/jvm.options \
    && sed -i 's/-Xmx1g/-Xmx4g/g' /usr/share/logstash/config/jvm.options

RUN sed -i "\$a\ " /usr/share/logstash/config/pipelines.yml 
RUN sed -i "\$a- pipeline.id: elastiflow" /usr/share/logstash/config/pipelines.yml 
RUN sed -i "\$a\ \ path.config: /usr/share/logstash/elastiflow/conf.d/*.conf" /usr/share/logstash/config/pipelines.yml

# RUN curl -X POST  http://kibana:5601/api/kibana/dashboards/import -H "Content-Type: application/json" -H "kbn-xsrf: true" -d @/tmp/elastiflow-master/kibana/elastiflow.dashboards.6.4.x.json